name: Update AdFilt File

on:
  schedule:
    - cron: '0 * * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up caching
        id: cache-hash
        uses: actions/cache@v3
        with:
          path: hash.txt
          key: hash-${{ runner.os }}
          restore-keys: hash-${{ runner.os }}

      - name: Download latest file
        run: |
          curl -s -o AntiMalwareAdGuardHome.txt "https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt"

      - name: Compute hash
        run: |
          sha256sum AntiMalwareAdGuardHome.txt | awk '{print $1}' > new_hash.txt

      - name: Check for changes
        id: check_changes
        run: |
          if [ ! -f hash.txt ]; then
            echo "First run or cache miss detected. Treating as change."
            echo "changed=true" >> $GITHUB_ENV
          elif cmp -s hash.txt new_hash.txt; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi
          mv new_hash.txt hash.txt

      - name: Save new hash to cache
        if: env.changed == 'true'
        uses: actions/cache@v3
        with:
          path: hash.txt
          key: hash-${{ runner.os }}-${{ github.run_id }}

      - name: Extract relevant lines
        if: env.changed == 'true'
        run: |
          grep -E '^\|\|.*\^$' AntiMalwareAdGuardHome.txt | sort -u > adfilt

      - name: Commit and push changes
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add adfilt
          git commit -m "Adfilt Definition Update"
          git push
