name: Update AdFilt File

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up caching
        uses: actions/cache@v3
        with:
          path: adfilt
          key: adfilt-${{ runner.os }}-${{ github.run_id }}
          restore-keys: adfilt-${{ runner.os }}

      - name: Download latest file
        run: |
          curl -s -o AntiMalwareAdGuardHome.txt "https://raw.githubusercontent.com/DandelionSprout/adfilt/refs/heads/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt"

      - name: Extract relevant lines
        run: |
          grep -E '^\|\|.*\^$' AntiMalwareAdGuardHome.txt | sort -u > adfilt

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet adfilt; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add adfilt
          git commit -m "Updated adfilt file"
          git push
